### ISSUE TITLE
Mismatch of names of the binary and package

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#479]
I'm doing this:

```
stack install --resolver lts-22.16 eo-phi-normalizer
```

I expect to have `eo-phi-normalizer` to be installed. However, I'm getting this file:

```
~/.local/bin/normalizer
```

Would be good to renamed it to `eo-phi-normalizer`, I believe.

**Comment by yegor256** [comment]
@deemp please, pay attention

**Comment by deemp** [comment]
@yegor256 Haskell packages may expose multiple executables. Hence, it's not mandatory to use the same name for a package and an executable.

I prefer the name `normalizer` because it implies less typing.

However, this name is also used for the [charset_normalizer](https://github.com/jawah/charset_normalizer#-basic-usage) executable that was installed on my machine, and one of my teammates was confused about getting a message from that executable after running `normalizer --help`.

> I expect to have eo-phi-normalizer to be installed. 

Please explain why you expected an executable with this name to be installed. Perhaps we need to improve our documentation on Installation ([link](https://www.objectionary.com/normalizer/docs/installation.html)).

**Comment by yegor256** [comment]
@deemp it seems reasonable to install XYZ and then run XYZ. Just easier to remember. I also have the same collision of names on my machine with `charset_normalizer` -- this situation makes it impossible to run `normalizer` (I have to call it using full path, thus _more_ typing, not less)
